# Generated by Django 2.2.5 on 2019-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
