# Generated by Django 2.2.5 on 2019-10-04 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15, null=True)),
                ('mname', models.CharField(max_length=15, null=True)),
                ('lname', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('email_id', models.CharField(max_length=25, null=True)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
