# Generated by Django 2.2.5 on 2019-10-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_user_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
